import type { Metadata } from 'next'
import { Playfair_Display, Inter } from 'next/font/google'
import Script from 'next/script'
import './globals.css'

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  display: 'swap',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

// Con www: el ápice responde 307 y manda aquí. Apuntar el canónico, los
// idiomas alternos y el mapa del sitio a una dirección que primero redirige
// diluye la señal en vez de declarar el destino final.
const siteUrl = 'https://www.marimbashome.com'
const ogImage = `${siteUrl}/opengraph-image`

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: 'Marimbas Home — Tu Hogar en México',
  description:
    'Departamentos y casas para tu próxima estancia en Ciudad de México y Chiapas. Más de 5,000 huéspedes confían en Marimbas Home desde 2015.',
  keywords: [
    'Marimbas Home',
    'renta vacacional México',
    'Airbnb Condesa',
    'Airbnb Tuxtla',
    'hospedaje CDMX',
    'hospedaje Chiapas',
    'departamentos CDMX',
    'casas Tuxtla',
  ],
  authors: [{ name: 'Marimbas Home' }],
  verification: {
    google: 'google4a0dc3d8d43a19b2',
  },
  alternates: {
    canonical: siteUrl,
    // Sin alternante 'en': apuntaba a esta misma dirección, que desde el
    // servidor solo sirve español (el cambio de idioma es un botón que actúa en
    // el navegador y nunca cambia la URL). Declarar una traducción que los
    // buscadores no pueden ver es una promesa falsa; se declara lo que hay.
    languages: {
      'es-MX': siteUrl,
      'x-default': siteUrl,
    },
  },
  openGraph: {
    title: 'Marimbas Home — Tu Hogar en México',
    description:
      'Espacios con carácter en CDMX y Chiapas. Check-in digital, atención personal, más de 10 años de experiencia.',
    type: 'website',
    url: siteUrl,
    siteName: 'Marimbas Home',
    locale: 'es_MX',
    // og:image auto-generated by app/opengraph-image.tsx (Next.js 14 convention)
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Marimbas Home — Tu Hogar en México',
    description:
      'Departamentos y casas en CDMX y Chiapas. Más de 5,000 huéspedes desde 2015.',
    // twitter:image auto-inherited from opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'LodgingBusiness',
  name: 'Marimbas Home',
  url: siteUrl,
  logo: `${siteUrl}/opengraph-image`,
  image: ogImage,
  description:
    // Sin cifras a mano: este texto no se puede derivar aquí y un número
    // escrito se pudre en semanas (decía 28, luego 27, y la base iba en 25).
    'Operador de hospedaje de renta vacacional en Ciudad de México y Chiapas desde 2015.',
  foundingDate: '2015-05',
  areaServed: [
    { '@type': 'City', name: 'Ciudad de México' },
    { '@type': 'City', name: 'Tuxtla Gutiérrez' },
    { '@type': 'City', name: 'Berriozabal' },
    { '@type': 'City', name: 'Ocozocoautla' },
  ],
  sameAs: [
    'https://book.marimbashome.com',
    'https://propietarios.marimbashome.com',
    'https://www.airbnb.com/users/show/9849014',
  ],
}

const websiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Marimbas Home',
  url: siteUrl,
  inLanguage: 'es-MX',
  publisher: {
    '@type': 'Organization',
    name: 'Marimbas Home',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es" className={`${playfair.variable} ${inter.variable}`}>
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="sitemap" type="application/xml" href={`${siteUrl}/sitemap.xml`} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
      </head>
      <body>
        {children}
        {/* Google Analytics 4 */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-Q1NXNXMPMS"
          strategy="afterInteractive"
        />
        <Script id="ga4-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-Q1NXNXMPMS');
          `}
        </Script>
      </body>
    </html>
  )
}
